import type { Recipe } from '@/types/recipe';

export const mockRecipes: Recipe[] = [
  {
    id: '1',
    name: 'Mercimek Çorbası',
    emoji: '🍲',
    kcal: 220,
    servings: 4,
    time_min: 35,
    macros: { protein: 12, karb: 30, yag: 6 },
    match_pct: 95,
    ingredients: [
      'Kırmızı mercimek',
      'Soğan',
      'Havuç',
      'Tereyağı',
      'Tuz, kırmızı biber',
    ],
    steps: [
      'Soğan ve havucu ince doğrayıp tereyağında kavurun.',
      'Yıkanmış mercimeği ekleyip birkaç dakika daha kavurun.',
      'Sıcak su ekleyip mercimek yumuşayana kadar pişirin.',
      'Blenderdan geçirip pürüzsüz hale getirin.',
      'Tuzunu ayarlayıp sıcak servis edin.',
    ],
  },
  {
    id: '2',
    name: 'Karnıyarık',
    emoji: '🍆',
    kcal: 410,
    servings: 4,
    time_min: 70,
    macros: { protein: 22, karb: 18, yag: 26 },
    match_pct: 78,
    ingredients: [
      'Patlıcan',
      'Kıyma',
      'Soğan',
      'Domates',
      'Sivri biber',
    ],
    steps: [
      'Patlıcanları soyup şeritler halinde kabuk bırakarak kızgın yağda kızartın.',
      'Soğanı kavurup kıymayı ekleyerek pişirin.',
      'Domates ve biberi ekleyip iç harcı hazırlayın.',
      'Kızarmış patlıcanları yarıp içine harcı doldurun.',
      'Üzerine domates dilimleri koyup fırında pişirin.',
    ],
  },
  {
    id: '3',
    name: 'Menemen',
    emoji: '🍳',
    kcal: 280,
    servings: 2,
    time_min: 15,
    macros: { protein: 14, karb: 10, yag: 20 },
    match_pct: 100,
    ingredients: ['Yumurta', 'Domates', 'Yeşil biber', 'Zeytinyağı', 'Tuz'],
    steps: [
      'Biberleri zeytinyağında kavurun.',
      'Rendelenmiş domatesi ekleyip suyunu çekene kadar pişirin.',
      'Yumurtaları kırıp karıştırarak pişirin.',
      'Tuzunu ekleyip sıcak servis edin.',
    ],
  },
  {
    id: '4',
    name: 'Tavuk Sote',
    emoji: '🍗',
    kcal: 350,
    servings: 3,
    time_min: 30,
    macros: { protein: 32, karb: 12, yag: 16 },
    match_pct: 65,
    ingredients: [
      'Tavuk göğsü',
      'Soğan',
      'Yeşil biber',
      'Mantar',
      'Zeytinyağı',
    ],
    steps: [
      'Tavuk göğsünü küp küp doğrayın.',
      'Zeytinyağında soğanı pembeleşene kadar kavurun.',
      'Tavukları ekleyip rengi dönene kadar pişirin.',
      'Biber ve mantarı ekleyip birkaç dakika daha pişirin.',
      'Baharatlarını ekleyip sıcak servis edin.',
    ],
  },
  {
    id: '5',
    name: 'Ezogelin Çorbası',
    emoji: '🥣',
    kcal: 195,
    servings: 4,
    time_min: 40,
    macros: { protein: 10, karb: 28, yag: 5 },
    match_pct: 58,
    ingredients: [
      'Kırmızı mercimek',
      'Pirinç',
      'Bulgur',
      'Soğan',
      'Salça',
    ],
    steps: [
      'Soğanı kavurup salçayı ekleyin.',
      'Mercimek, pirinç ve bulguru ekleyip su ile karıştırın.',
      'Malzemeler yumuşayana kadar kısık ateşte pişirin.',
      'Blenderdan geçirip tekrar ısıtın.',
      'Nane ve pul biberli tereyağı ile servis edin.',
    ],
  },
  {
    id: '6',
    name: 'Fırında Sebzeli Tavuk',
    emoji: '🥘',
    kcal: 390,
    servings: 4,
    time_min: 50,
    macros: { protein: 30, karb: 20, yag: 18 },
    match_pct: 42,
    ingredients: [
      'Tavuk but',
      'Patates',
      'Havuç',
      'Kabak',
      'Zeytinyağı',
    ],
    steps: [
      'Sebzeleri iri doğrayıp fırın tepsisine dizin.',
      'Tavukları baharatlayıp sebzelerin üzerine yerleştirin.',
      'Zeytinyağı gezdirip önceden ısıtılmış fırına verin.',
      'Tavuklar ve sebzeler pişene kadar fırınlayın.',
      'Sıcak olarak servis edin.',
    ],
  },
];
