import type { Recipe } from '@/types/recipe';

// Kademeli 9 tarif yapısını yansıtır: 3x match_pct=100, 3x 75-99, 3x 50-74.
export const mockRecipes: Recipe[] = [
  {
    id: '1',
    name: 'Menemen',
    emoji: '🍳',
    kcal: 280,
    servings: 2,
    time_min: 15,
    difficulty: 'Kolay',
    macros: { protein: 14, karb: 10, yag: 20 },
    match_pct: 100,
    ingredients: [
      { name: 'Yumurta', in_inventory: true },
      { name: 'Domates', in_inventory: true },
      { name: 'Yeşil biber', in_inventory: true },
      { name: 'Zeytinyağı', in_inventory: true },
      { name: 'Tuz', in_inventory: true },
    ],
    missing_count: 0,
    steps: [
      'Biberleri zeytinyağında kavurun.',
      'Rendelenmiş domatesi ekleyip suyunu çekene kadar pişirin.',
      'Yumurtaları kırıp karıştırarak pişirin.',
      'Tuzunu ekleyip sıcak servis edin.',
    ],
    chef_tip: 'Domatesin suyunu iyice çektirirseniz menemen sulanmaz.',
  },
  {
    id: '2',
    name: 'Sahanda Yumurta',
    emoji: '🍳',
    kcal: 210,
    servings: 1,
    time_min: 8,
    difficulty: 'Kolay',
    macros: { protein: 13, karb: 2, yag: 17 },
    match_pct: 100,
    ingredients: [
      { name: 'Yumurta', in_inventory: true },
      { name: 'Tereyağı', in_inventory: true },
      { name: 'Tuz, karabiber', in_inventory: true },
    ],
    missing_count: 0,
    steps: [
      'Tereyağını tavada eritin.',
      'Yumurtaları kırıp kısık ateşte pişirin.',
      'Tuz ve karabiber serpip servis edin.',
    ],
    chef_tip: 'Kısık ateş, beyazı sertleşmeden sarısının kıvamlı kalmasını sağlar.',
  },
  {
    id: '3',
    name: 'Domates Salatası',
    emoji: '🥗',
    kcal: 120,
    servings: 2,
    time_min: 10,
    difficulty: 'Kolay',
    macros: { protein: 2, karb: 8, yag: 9 },
    match_pct: 100,
    ingredients: [
      { name: 'Domates', in_inventory: true },
      { name: 'Yeşil biber', in_inventory: true },
      { name: 'Zeytinyağı', in_inventory: true },
      { name: 'Tuz', in_inventory: true },
    ],
    missing_count: 0,
    steps: [
      'Domates ve biberleri doğrayın.',
      'Zeytinyağı ve tuzla harmanlayıp servis edin.',
    ],
    chef_tip: 'Domatesleri buzdolabından çıkarıp oda sıcaklığında kullanırsanız aroması artar.',
  },
  {
    id: '4',
    name: 'Mercimek Çorbası',
    emoji: '🍲',
    kcal: 220,
    servings: 4,
    time_min: 35,
    difficulty: 'Kolay',
    macros: { protein: 12, karb: 30, yag: 6 },
    match_pct: 80,
    ingredients: [
      { name: 'Kırmızı mercimek', in_inventory: true },
      { name: 'Soğan', in_inventory: true },
      { name: 'Havuç', in_inventory: false },
      { name: 'Tereyağı', in_inventory: true },
      { name: 'Tuz, kırmızı biber', in_inventory: true },
    ],
    missing_count: 1,
    steps: [
      'Soğan ve havucu ince doğrayıp tereyağında kavurun.',
      'Yıkanmış mercimeği ekleyip birkaç dakika daha kavurun.',
      'Sıcak su ekleyip mercimek yumuşayana kadar pişirin.',
      'Blenderdan geçirip pürüzsüz hale getirin.',
      'Tuzunu ayarlayıp sıcak servis edin.',
    ],
    chef_tip: 'Blenderdan geçirmeden önce birkaç kaşık ayırırsanız çorbaya doku katabilirsiniz.',
  },
  {
    id: '5',
    name: 'Tavuk Sote',
    emoji: '🍗',
    kcal: 350,
    servings: 3,
    time_min: 30,
    difficulty: 'Kolay',
    macros: { protein: 32, karb: 12, yag: 16 },
    match_pct: 80,
    ingredients: [
      { name: 'Tavuk göğsü', in_inventory: true },
      { name: 'Soğan', in_inventory: true },
      { name: 'Yeşil biber', in_inventory: true },
      { name: 'Mantar', in_inventory: false },
      { name: 'Zeytinyağı', in_inventory: true },
    ],
    missing_count: 1,
    steps: [
      'Tavuk göğsünü küp küp doğrayın.',
      'Zeytinyağında soğanı pembeleşene kadar kavurun.',
      'Tavukları ekleyip rengi dönene kadar pişirin.',
      'Biber ve mantarı ekleyip birkaç dakika daha pişirin.',
      'Baharatlarını ekleyip sıcak servis edin.',
    ],
    chef_tip: 'Tavukları yüksek ateşte kısa süre pişirmek etin kurumasını önler.',
  },
  {
    id: '6',
    name: 'Karnıyarık',
    emoji: '🍆',
    kcal: 410,
    servings: 4,
    time_min: 70,
    difficulty: 'Orta',
    macros: { protein: 22, karb: 18, yag: 26 },
    match_pct: 75,
    ingredients: [
      { name: 'Patlıcan', in_inventory: false },
      { name: 'Kıyma', in_inventory: true },
      { name: 'Soğan', in_inventory: true },
      { name: 'Domates', in_inventory: true },
      { name: 'Sivri biber', in_inventory: true },
    ],
    missing_count: 1,
    steps: [
      'Patlıcanları soyup şeritler halinde kabuk bırakarak kızgın yağda kızartın.',
      'Soğanı kavurup kıymayı ekleyerek pişirin.',
      'Domates ve biberi ekleyip iç harcı hazırlayın.',
      'Kızarmış patlıcanları yarıp içine harcı doldurun.',
      'Üzerine domates dilimleri koyup fırında pişirin.',
    ],
    chef_tip: 'Patlıcanları kızartmadan önce tuzlu suda bekletirseniz daha az yağ çeker.',
  },
  {
    id: '7',
    name: 'Ezogelin Çorbası',
    emoji: '🥣',
    kcal: 195,
    servings: 4,
    time_min: 40,
    difficulty: 'Orta',
    macros: { protein: 10, karb: 28, yag: 5 },
    match_pct: 60,
    ingredients: [
      { name: 'Kırmızı mercimek', in_inventory: true },
      { name: 'Pirinç', in_inventory: false },
      { name: 'Bulgur', in_inventory: false },
      { name: 'Soğan', in_inventory: true },
      { name: 'Salça', in_inventory: true },
    ],
    missing_count: 2,
    steps: [
      'Soğanı kavurup salçayı ekleyin.',
      'Mercimek, pirinç ve bulguru ekleyip su ile karıştırın.',
      'Malzemeler yumuşayana kadar kısık ateşte pişirin.',
      'Blenderdan geçirip tekrar ısıtın.',
      'Nane ve pul biberli tereyağı ile servis edin.',
    ],
    chef_tip: 'Salçayı yağda biraz kavurmak çorbaya daha derin bir tat katar.',
  },
  {
    id: '8',
    name: 'Fırında Sebzeli Tavuk',
    emoji: '🥘',
    kcal: 390,
    servings: 4,
    time_min: 50,
    difficulty: 'Orta',
    macros: { protein: 30, karb: 20, yag: 18 },
    match_pct: 60,
    ingredients: [
      { name: 'Tavuk but', in_inventory: true },
      { name: 'Patates', in_inventory: false },
      { name: 'Havuç', in_inventory: false },
      { name: 'Kabak', in_inventory: true },
      { name: 'Zeytinyağı', in_inventory: true },
    ],
    missing_count: 2,
    steps: [
      'Sebzeleri iri doğrayıp fırın tepsisine dizin.',
      'Tavukları baharatlayıp sebzelerin üzerine yerleştirin.',
      'Zeytinyağı gezdirip önceden ısıtılmış fırına verin.',
      'Tavuklar ve sebzeler pişene kadar fırınlayın.',
      'Sıcak olarak servis edin.',
    ],
    chef_tip: 'Sebzeleri eşit büyüklükte doğrarsanız aynı sürede pişerler.',
  },
  {
    id: '9',
    name: 'Sebzeli Makarna',
    emoji: '🍝',
    kcal: 430,
    servings: 3,
    time_min: 25,
    difficulty: 'Kolay',
    macros: { protein: 13, karb: 62, yag: 14 },
    match_pct: 50,
    ingredients: [
      { name: 'Makarna', in_inventory: false },
      { name: 'Domates', in_inventory: true },
      { name: 'Kabak', in_inventory: true },
      { name: 'Parmesan', in_inventory: false },
      { name: 'Sarımsak', in_inventory: false },
      { name: 'Zeytinyağı', in_inventory: true },
    ],
    missing_count: 3,
    steps: [
      'Makarnayı tuzlu suda haşlayın.',
      'Sebzeleri zeytinyağında soteleyin.',
      'Haşlanan makarnayı sebzelerle karıştırın.',
      'Üzerine rendelenmiş peynir serpip servis edin.',
    ],
    chef_tip: 'Makarna suyundan bir kepçe ayırıp sosa eklerseniz sos makarnaya daha iyi tutunur.',
  },
];
